<h1>Content Moderation</h1>

<p>Determine whether text contains any bad words.</p>

<p>Cost: FREE</p>

<h2>API Version 0</h2>

<p>Example GET request:</p>

<code>
https://content-moderation.monthly-basis.com/api/v0/contains-bad-words?string=hello+world<br>
</code>

<p>Example form:</p>

<form action="/api/v0/contains-bad-words" method="get">
    <input type="text" name="string">
    <input type="submit" value="Submit">
</form>
